---
deployment:
  tasks:
    - export DEPLOYVIEWSPATH=/home/sitejsvh/laravel1.sitesystemhub.com/resources/views
    - /bin/cp -r resources/views $DEPLOYVIEWSPATH
    - export DEPLOYROUTESPATH=/home/sitejsvh/laravel1.sitesystemhub.com/routes/
    - /bin/cp routes/web.php
